meta_product_name: "GoFlamingo"
meta_title: "GoFlamingo - Find and share travel experiences"
meta_description: "Goflamingo is THE website to find and share travel experiences. Find out what your friends and others did when they went on their amazing trip. Also setup and share your own trips!"
meta_image: "homebackground_1.jpeg" # should exist in `app/assets/images/`
